id: P62D62C3E
initial_creation_type: input
source_metadata:
  title: Calling the Guru from Afar
  language: fr
  description: 'Devotional texts belonging to the genre of Calling the Guru from Afar
    (bla ma rgyang ''bod):'
  volume:
    c3e8e9029a9f48c6b00f3175e4045639:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    d4dc5341c914459d8caaedd657ce3c59:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Prayers
    bfdc70a0532b47d5a93fc52e54581873:
      title: Calling the Guru From Afar
      parent: Prayers
    4ed63b1974de495684d368f298fb7154:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Prayers
    a00f9d48be0d4e30a14544801c241da9:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    20bd45fd45944b6f80ee1ba43c1a3c7e:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
    d37c474bf9bb4562a6e175079095474d:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    297a6400ae22467bbec9ec63fa7ef857:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Prayers
    3a31121553a94250976e2b3ca2a4d9de:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Prayers
    64451df910494d00bcb3a6a9fc4aa350:
      title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling
        the Guru from Afar'
      parent: Prayers
    4d67e9e2f14f47ed86637a55d99131fe:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Prayers
    e61ed537ae9d49fc9bd8d34641badc55:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    5ce09e008182407fadf016b1df587a2d:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Prayers
    caf06d4c7a5e49e3ab1779aa03124c72:
      title: Calling the Guru from Afar
      parent: Prayers
created_at: '2022-03-01T03:10:18.231561'
last_modified_at: '2022-03-01T03:10:18.231563'
